import axios from "axios";

/**
 * Make a call to the sevDesk API
 *
 * @param {string} path
 * @param {string} apiToken
 * @param {object} config
 * @returns
 */
const makeApiCall = (path, apiToken, config = {}) => {
  return axios.get(`https://my.sevdesk.de/api/v1/${path}`, {
    headers: {
      Authorization: apiToken,
      ...(config.headers || {}),
    },
    ...config,
  });
};

/**
 * Returns all vouchers in a specific payDate-range
 *
 * @param {Date} startDate
 * @param {Date} endDate
 * @param {string} apiToken
 * @returns {Array} Voucher objects as defined in sevDesk API
 */
const getVouchers = async (startDate, endDate, apiToken) => {
  try {
    const result = await makeApiCall("Voucher", apiToken, {
      params: {
        startPayDate: startDate.getTime() / 1000,
        endPayDate: endDate.getTime() / 1000,
      },
    });

    return result.data.objects;
  } catch (err) {
    throw new Error(err.message);
  }
};

/**
 * Returns all invoices in a specific payDate-range
 * sevDesk API does not allow filtering invoices by payDate
 * therefore geht invoices from the range and the range before that
 * and than manually filter by payDate, this should be enough to get most invoices
 *
 * @param {Date} startPayDate
 * @param {Date} endPayDate
 * @param {string} apiToken
 * @returns {Array} Invoice objects as defined in sevDesk API
 */
const getInvoices = async (startPayDate, endPayDate, apiToken) => {
  const timeRangeLength = endPayDate.getTime() - startPayDate.getTime();
  const startDate = new Date(startPayDate.getTime() - 2 * timeRangeLength);
  try {
    const result = await makeApiCall("Invoice", apiToken, {
      params: {
        startDate: startDate.getTime() / 1000,
        endDate: endPayDate.getTime() / 1000,
      },
    });

    const invoices = result.data.objects;
    const filteredInvoices = invoices.filter((invoice) => {
      if (!invoice.payDate) {
        return false;
      }
      const invoicePayDate = new Date(invoice.payDate);
      if (!invoicePayDate) {
        return false;
      }
      return invoicePayDate >= startPayDate && invoicePayDate <= endPayDate;
    });

    return filteredInvoices;
  } catch (err) {
    throw new Error(err.message);
  }
};

/**
 * Downloads all the passed vouchers/invoices as PDF + meta data for storage
 * Does NOT store the files
 *
 * @param {string} type of object ("vouchers" or "invoices")
 * @param {Array} vouchers/invoices from API / @see getVouchers
 * @returns {Array} for each voucher: PDF Buffer Data and meta data (payDate, supplierName, documentId)
 */
const downloadDocuments = async (objectType, objects, apiToken) => {
  let documents = [];
  try {
    const promises = objects.map((object) => {
      return downloadDocument(objectType, object, apiToken);
    });
    documents = await Promise.all(promises);
  } catch (err) {
    throw err;
  }
  return documents.filter((vd) => vd); // filter out null values - values without a document attached
};

/**
 * Private. Downloads a single document
 * @see downloadDocuments
 *
 * @param {string} type of object ("vouchers" or "invoices")
 * @param {Object} voucher (@see getVouchers) or invoices (@see getInvoices)
 * @returns {Object} PDF Buffer Data and meta data (payDate, supplierName, documentId)
 */
const downloadDocument = async (objectType, object, apiToken) => {
  try {
    let result = null;
    if (objectType === "vouchers") {
      result = await makeApiCall(
        `Voucher/${object.id}/downloadDocument`,
        apiToken
      );
    } else if (objectType === "invoices") {
      result = await makeApiCall(`Invoice/${object.id}/getPdf`, apiToken);
    }

    if (!result) {
      return null;
    }

    const document = result.data.objects;
    if (!document) {
      // values without a document attached - eg transaction costs automatically generated by sevDesk - ignore them
      return null;
    }
    let content = document.content;
    if (document.base64Encoded) {
      content = Buffer.from(content, "base64");
    }
    let name = "";
    if (objectType === "vouchers") {
      name = object.supplierName || object.supplierNameAtSave || "";
    } else if (objectType === "invoices") {
      name = object.addressName || "";
    }

    return {
      document: content,
      payDate: object.payDate ? new Date(object.payDate) : null,
      name: name,
      id: object.id,
    };
  } catch (err) {
    return null;
  }
};

export { getVouchers, getInvoices, downloadDocuments };
